server:
  error:
    include-message: always                               # enable showing all errors (helps when troubleshooting)
    include-binding-errors: always                        # it should be turned off when the app is deployed (vulnerability)

spring:
  datasource:                                             # connection to the database
    username: postgres                                    # user
    password: password                                    # password
    url: jdbc:postgresql://localhost:5432/pia-silhavyj    # the database is running in a Docker container
                                                          # with port 5432 exposed to the local machine
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2dll:
          create_namespaces: true                         # create database schema if it doesn't exist
    show-sql: true

  mail:
    host: localhost                                       # the mail server is running in a Docker container
    port: 25                                              # with post 25 exposed to the local machine
    username: admin                                       # username
    password: 123                                         # password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  url:  http://localhost:8080
  senderemail: socialnetwork@silhavyj.pia.kiv.zcu.cz     # email address of the sender
  searchnameminlen: 3                                    # at least 3 letters must be provided when search a person
  resetpasswordexpirationtime: 5                         # when resetting a password, the user has 5 mins to do so until the token expires
  poststodisplayonprofilepage: 10                        # number of posts to be shown on the profile page

  users:                                                 # default users that will be added to the database
    -                                                    # automatically when the application starts
      firstname: user1
      lastname: user1
      password: User1-123*
      email: user1@silhavyj.pia.kiv.zcu.cz
      dob: "2006-10-27"
      role: USER
      gender: MALE
      profilepicturepath: images/profile_pic1.png

    -
      firstname: user2
      lastname: user2
      password: User2-123*
      email: user2@silhavyj.pia.kiv.zcu.cz
      dob: "1998-04-09"
      role: USER
      gender: MALE
      profilepicturepath: images/profile_pic2.png

    -
      firstname: user3
      lastname: user3
      password: User3-123*
      email: user3@silhavyj.pia.kiv.zcu.cz
      dob: "1994-04-10"
      role: USER
      gender: FEMALE
      profilepicturepath: images/profile_pic3.png

    - firstname: admin
      lastname: admin
      password: Admin123*
      email: admin@silhavyj.pia.kiv.zcu.cz
      dob: "1994-04-15"
      role: ADMIN
      gender: MALE
      profilepicturepath: images/profile_pic4.png